# Generated by Django 3.1.5 on 2021-01-24 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='slug')),
                ('body', models.TextField(max_length=1500, verbose_name='Содержание')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('replying_tweet', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='twitter.tweet', verbose_name='Replying to')),
            ],
            options={
                'verbose_name': 'Твит',
                'verbose_name_plural': 'Твиты',
                'ordering': ['-date'],
            },
        ),
    ]
